Add login form and validation
yuliiapavlyk/AngularProject pull request #20
Opened 2019-09-14 18:53 UTC by skrebetsnataliia

2019-09-16 16:29 UTC, Benkevych requested changes

2019-09-16 16:29 UTC, Benkevych commented on src/modules/auth/auth.module.ts
> +    path: '',
path to login page should be '/login'

2019-09-16 16:29 UTC, Benkevych commented on src/pages/auth/login/login.component.ts
> +  if (this.show){
this check is not needed, you can remove property 'type' and check 'show' directly in html

2019-09-16 16:29 UTC, Benkevych commented on src/pages/auth/login/login.component.html
> +            <input type="{{type}}"
<input type="{{show ? 'text' : 'password'}}"

2019-09-16 16:29 UTC, Benkevych commented on src/pages/header/header.component.html
> +    <a routerLink="/login" class="header-link_logout">Log out</a>
you should not only redirect user to login page, but also remove token from browser storage(add logout method to user service and redirect to login after token removed)

2019-09-16 16:29 UTC, Benkevych commented on src/services/token-interceptor.service.ts
> +        Authorization: `Barber ${userService.getToken()}`
add check if there is token... if there is none, value will be false, in case if there is no token - redirect to login page

2019-09-18 06:33 UTC, DmytroRoik commented on src/pages/auth/login/login.component.ts
> +  const valueForm=this.myGroup.value;
краще замінити на const { value }=this.myGroup; набагато коротший запис

const value = this.myGroup.value; 
теж саме що і:
const { value }=this.myGroup;

2019-09-18 06:34 UTC, DmytroRoik commented on src/pages/auth/login/login.component.ts
> +accessToken="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QxQG1haWwuY29tIiwiaWF0IjoxNTY4NTY5MTg3LCJleHAiOjE1Njg2NTU1ODd9.CLo_uHV9kncr5YAXliP_H8r6h4JpA0SYBOjMNUiJSKE";
accessToken не має бути тут (має витягуватись/ записуватись в localStorage або sessionStorage)

2019-09-18 06:34 UTC, DmytroRoik commented on src/pages/auth/login/login.component.ts
> +              console.log(res);
console.log(res); погана практика залишати console.log в коді

2019-09-18 06:39 UTC, DmytroRoik commented on src/services/user.service.ts
> +logIn(user){
потрібно всюди додавати типізацію (стосується всіх запитів). щось типу logIn(user): Observable<{data: blabla}>{}

2019-09-18 10:09 UTC, DmytroRoik commented on src/services/user.service.ts
> +logIn(user):Observable<any>{
Має бути якось так
logIn(user): Observable<{ accessToken: string }>{
  return this.http.post<{ accessToken: string }>(`${this.API_URL}/signin`, user)
}

2019-09-18 10:58 UTC, merged