added validation to register page
yuliiapavlyk/AngularProject pull request #21
Opened 2019-09-16 09:56 UTC by yuliiapavlyk

Logic will be added after @skrebetsnataliia  pull request will be complete.

2019-09-16 16:34 UTC, Benkevych requested changes

2019-09-16 16:34 UTC, Benkevych commented on src/pages/auth/register/register.component.html
> +          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
isn't it register form?

2019-09-16 16:34 UTC, Benkevych commented on src/pages/auth/register/register.component.ts
> +  confirmPassword:boolean = false;
remove

2019-09-16 16:34 UTC, Benkevych commented on src/pages/auth/register/register.component.ts
> +    if(this.loginForm.value.password == this.loginForm.value.confirm){
add password match validator to form
https://stackoverflow.com/a/51606362

2019-09-16 17:09 UTC, yuliiapavlyk commented on src/pages/auth/register/register.component.html
> +          <form [formGroup]="loginForm" (ngSubmit)="onSubmit()">
@Benkevych  fixed.

2019-09-16 17:09 UTC, yuliiapavlyk commented on src/pages/auth/register/register.component.ts
> +  confirmPassword:boolean = false;
@Benkevych  removed.

2019-09-18 06:44 UTC, DmytroRoik commented on src/pages/auth/register/register.component.ts
> +    let password = registerForm.get('password').value;
має бути const, a не let (посилання на змінну або значення змінної не змінюється)

2019-09-18 07:48 UTC, yuliiapavlyk commented on src/pages/auth/register/register.component.ts
> +    let password = registerForm.get('password').value;
@DmytroRoik fixed.

2019-09-18 07:53 UTC, merged